### ISSUE TITLE
Mac support for browser installed via homebrew

### ISSUE THREAD

**Issue by lakuapik** [gluon-framework/gluon#18] opened 2023-01-03 02:05 UTC
I installed my browser (firefox and chrome) via homebrew, when i run the gluworld example. i got error:

<img width="1303" alt="image" src="https://user-images.githubusercontent.com/20186786/210291453-7ab8560c-95dc-49d1-aed0-e229b1b6ba18.png">

```txt

❯ node .
[Gluon] starting browser...
file:///Users/d/Data/labs/glutonis/node_modules/@gluon-framework/gluon/src/index.js:86
  const [ browserPath, browserName ] = await findBrowserPath(forceBrowser);
                                       ^

TypeError: (intermediate value) is not iterable
    at startBrowser (file:///Users/d/Data/labs/glutonis/node_modules/@gluon-framework/gluon/src/index.js:86:40)
    at async Module.open (file:///Users/d/Data/labs/glutonis/node_modules/@gluon-framework/gluon/src/index.js:114:19)
    at async file:///Users/d/Data/labs/glutonis/index.js:38:19
```

**Comment by twisttaan** [comment] 2023-01-03 02:07
![image](https://user-images.githubusercontent.com/69066026/210291597-7161786e-f7f2-45bb-90c8-3fdd26bfe9fe.png)
Can replicate

**Comment by twisttaan** [comment] 2023-01-03 02:07
What node version are you using?

**Comment by twisttaan** [comment] 2023-01-03 02:08
The examples seem to be using v19
![image](https://user-images.githubusercontent.com/69066026/210291643-1144d8fd-4381-4afb-8886-ef8bba98d047.png)

**Comment by lakuapik** [comment] 2023-01-03 02:08
> What node version are you using?

v16.17.0

**Comment by twisttaan** [comment] 2023-01-03 02:08
I'm going to try 19, I'll let you know how it goes.

**Comment by twisttaan** [comment] 2023-01-03 02:09
Same problem

**Comment by artamonovtech** [comment] 2023-01-03 06:43
The issue is with the path for the Homebrew apps folders.

**Comment by bolshoytoster** [comment] 2023-01-03 11:52
@artamonovtech would it not be possible to find the executables from the PATH environment variable? Something like the [which npm package](https://www.npmjs.com/package/which).

[(Or the code if you don't want to add another dependency)](https://github.com/npm/node-which/blob/33d59bf90ce59c803dc5b6169a999f3895cf0d6f/lib/index.js#L49-L77)

**Comment by CanadaHonk** [comment] 2023-01-03 11:54
Gluon already has support for starting browsers in path. Are Mac browsers (installed via homebrew) in path?

**Comment by lakuapik** [comment] 2023-01-03 13:29
@CanadaHonk i believe its not:

<img width="662" alt="image" src="https://user-images.githubusercontent.com/20186786/210366555-39804b5b-9aa4-4df6-9047-5902e86771b4.png">

**Comment by artamonovtech** [comment] 2023-01-03 17:04
I chose to install Firefox from Homebrew:

<img width="607" alt="Screenshot 2023-01-03 at 23 02 01" src="https://user-images.githubusercontent.com/47431914/210404924-92baa8c0-2489-4e74-989d-254debdb8218.png">

**Comment by CanadaHonk** [comment] 2023-01-20 20:13
Seems to be resolved with last path finding rewrite.

**Closed by CanadaHonk** 2023-01-20 20:13 UTC
Labels: enhancement
